# See https://pre-commit.com/ for usage and config
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [manual, commit]
        language: system
        entry: pipenv run isort
        types: [python]
        args: ["--profile", "black"]

      - id: black
        name: black
        stages: [manual, commit]
        language: system
        entry: pipenv run black --line-length 120
        types: [python]

      - id: flake8
        name: flake8
        stages: [manual, commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [manual, commit]
        language: system
        entry: pipenv run mypy
        types: [python]
        require_serial: true

      - id: pytest
        name: pytest
        stages: [manual, push]
        language: system
        entry: pipenv run pytest
        types: [python]
        pass_filenames: false
